[package]
name = "salt_miner"
version = "0.1.0"
edition = "2021"

[dependencies]
web3 = "0.19.0"
rayon = "1.10.0"
sha3 = "0.10.8"
hex = "0.4.3"
indicatif = "0.17"
clap = { version = "4.5.7", features = ["derive"] }